//! the html sink: a static archive you can open in a browser.
//!
//! one file, no server, no javascript. the whole point of this format is that
//! `open archive.html` works on a machine with nothing installed, which is the
//! situation most of the time someone is looking at their own archive.
//!
//! what it contains:
//!
//! - a header with the count and the date range
//! - a search box that filters the list, in about twenty lines of plain
//!   javascript, because a list of ten thousand items with no filter is not an
//!   archive you can use
//! - one section per day, newest first, with every item
//!
//! everything is escaped on the way out. the text comes from the open web.

use std::path::PathBuf;
use std::sync::Mutex;

use mbm_core::bookmark::Bookmark;
use mbm_core::error::Result;
use mbm_core::medium::SinkMedium;
use mbm_core::port::{Sink, SinkReport};

use crate::{date_only, display_title, escape_html, summary_of, write_to};

/// the page shell, with `{items}` where the list goes.
///
/// kept in one string rather than built in pieces, because a css brace and a
/// format brace are the same character and a template is easier to read than an
/// append chain would be.
#[must_use]
pub fn page(items_html: &str, count: usize, first: Option<String>, last: Option<String>) -> String {
    let range = match (first, last) {
        (Some(a), Some(b)) => format!("{a} to {b}"),
        (Some(a), None) => a,
        _ => "unknown".to_owned(),
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>mebookmarker archive</title>
<style>
:root {{
  color-scheme: light dark;
  --fg: #16181d;
  --bg: #fdfdfc;
  --muted: #6b7280;
  --line: #e5e7eb;
  --accent: #1a56db;
}}
@media (prefers-color-scheme: dark) {{
  :root {{
    --fg: #e6e8eb;
    --bg: #131417;
    --muted: #9aa1ab;
    --line: #2a2d33;
    --accent: #8ab4f8;
  }}
}}
* {{ box-sizing: border-box; }}
body {{
  margin: 0;
  padding: 0 1.5rem 6rem;
  background: var(--bg);
  color: var(--fg);
  font: 16px/1.6 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
}}
main {{ max-width: 46rem; margin: 0 auto; }}
header {{ padding: 3rem 0 1.5rem; border-bottom: 1px solid var(--line); }}
h1 {{ font-size: 1.5rem; margin: 0 0 .25rem; letter-spacing: -0.01em; }}
.meta {{ color: var(--muted); font-size: .875rem; margin: 0; }}
#filter {{
  width: 100%;
  margin: 1.25rem 0 0;
  padding: .625rem .75rem;
  font: inherit;
  color: inherit;
  background: transparent;
  border: 1px solid var(--line);
  border-radius: .5rem;
}}
#filter:focus {{ outline: 2px solid var(--accent); outline-offset: 1px; }}
h2 {{
  font-size: .8125rem;
  text-transform: uppercase;
  letter-spacing: .06em;
  color: var(--muted);
  margin: 2.5rem 0 .25rem;
  font-weight: 600;
}}
article {{ padding: .875rem 0; border-bottom: 1px solid var(--line); }}
article:last-child {{ border-bottom: 0; }}
a {{ color: var(--accent); text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
.title {{ font-weight: 550; }}
.byline {{ color: var(--muted); font-size: .8125rem; margin: .125rem 0 0; }}
.excerpt {{
  margin: .5rem 0 0;
  color: var(--fg);
  opacity: .85;
  overflow-wrap: anywhere;
}}
.tags {{ margin-top: .5rem; display: flex; flex-wrap: wrap; gap: .375rem; }}
.tag {{
  font-size: .75rem;
  color: var(--muted);
  border: 1px solid var(--line);
  border-radius: 999px;
  padding: .0625rem .5rem;
}}
[hidden] {{ display: none !important; }}
footer {{ color: var(--muted); font-size: .8125rem; padding-top: 3rem; }}
</style>
</head>
<body>
<main>
<header>
  <h1>mebookmarker archive</h1>
  <p class="meta">{count} bookmarks · {range}</p>
  <input id="filter" type="search" placeholder="filter by title, text, tag, or author"
         autocomplete="off" autofocus>
</header>
{items_html}
<footer>generated by mebookmarker</footer>
</main>
<script>
const filter = document.getElementById('filter');
const items = Array.from(document.querySelectorAll('article'));
const days = Array.from(document.querySelectorAll('h2'));
filter.addEventListener('input', () => {{
  const needle = filter.value.trim().toLowerCase();
  for (const item of items) {{
    item.hidden = needle !== '' && !item.textContent.toLowerCase().includes(needle);
  }}
  // a day heading with nothing under it is noise
  for (const day of days) {{
    let next = day.nextElementSibling;
    let visible = false;
    while (next && next.tagName === 'ARTICLE') {{
      if (!next.hidden) {{ visible = true; break; }}
      next = next.nextElementSibling;
    }}
    day.hidden = !visible;
  }}
}});
</script>
</body>
</html>
"#
    )
}

/// one bookmark, as an `<article>`.
#[must_use]
pub fn article(bookmark: &Bookmark) -> String {
    use std::fmt::Write as _;

    let title = display_title(bookmark);
    let url = bookmark
        .url
        .as_ref()
        .map(ToString::to_string)
        .or_else(|| bookmark.links.first().map(|l| l.resolved.to_string()));

    let heading = match &url {
        Some(u) => {
            format!("<a class=\"title\" href=\"{}\">{}</a>", escape_html(u), escape_html(&title))
        }
        None => format!("<span class=\"title\">{}</span>", escape_html(&title)),
    };

    let mut byline = Vec::new();
    if let Some(when) = bookmark.created_at.or(Some(bookmark.ingested_at)) {
        byline.push(date_only(when));
    }
    if let Some(author) = &bookmark.author {
        byline.push(author.display());
    }
    if let Some(medium) = bookmark.source.collection.as_deref() {
        byline.push(medium.to_owned());
    }

    let mut out = String::with_capacity(bookmark.text.len() + 400);
    out.push_str("<article>");
    out.push_str(&heading);
    if !byline.is_empty() {
        let _ = write!(out, "<p class=\"byline\">{}</p>", escape_html(&byline.join(" · ")));
    }
    if let Some(summary) = summary_of(bookmark) {
        let _ = write!(out, "<p class=\"excerpt\">{}</p>", escape_html(summary));
    } else {
        let excerpt = excerpt(&bookmark.text);
        if !excerpt.is_empty() {
            let _ = write!(out, "<p class=\"excerpt\">{}</p>", escape_html(&excerpt));
        }
    }
    if !bookmark.tags.is_empty() {
        out.push_str("<div class=\"tags\">");
        for tag in bookmark.tags.iter().take(12) {
            let _ = write!(out, "<span class=\"tag\">{}</span>", escape_html(tag));
        }
        out.push_str("</div>");
    }
    out.push_str("</article>\n");
    out
}

/// the first line or two of a post, without its urls.
#[must_use]
pub fn excerpt(text: &str) -> String {
    let mut out = String::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with("http") {
            continue;
        }
        if !out.is_empty() {
            out.push(' ');
        }
        out.push_str(line);
        if out.chars().count() > 200 {
            break;
        }
    }
    if out.chars().count() > 240 {
        let cut: String = out.chars().take(237).collect();
        format!("{}…", cut.trim_end())
    } else {
        out
    }
}

/// the list, grouped by day, newest first.
#[must_use]
pub fn list(items: &[&Bookmark]) -> String {
    use std::fmt::Write as _;

    let mut days: Vec<i64> = Vec::new();
    for item in items {
        let day = item.created_at.unwrap_or(item.ingested_at) / 86_400_000;
        if !days.contains(&day) {
            days.push(day);
        }
    }
    days.sort_unstable();
    days.reverse();

    let mut out = String::new();
    for day in days {
        let _ = writeln!(out, "<h2>{}</h2>", date_only(day * 86_400_000));
        for item in
            items.iter().filter(|b| b.created_at.unwrap_or(b.ingested_at) / 86_400_000 == day)
        {
            out.push_str(&article(item));
        }
    }
    out
}

/// the whole document.
#[must_use]
pub fn document(items: &[&Bookmark]) -> String {
    let count = items.len();
    let mut days: Vec<i64> =
        items.iter().map(|b| b.created_at.unwrap_or(b.ingested_at) / 86_400_000).collect();
    days.sort_unstable();
    let first = days.first().map(|d| date_only(d * 86_400_000));
    let last = days.last().map(|d| date_only(d * 86_400_000));
    page(&list(items), count, first, last)
}

/// the html sink.
#[derive(Debug, Default)]
pub struct Html {
    path: PathBuf,
    items: Mutex<Vec<Bookmark>>,
}

impl Html {
    /// write to a path.
    #[must_use]
    pub fn new(path: impl Into<PathBuf>) -> Self {
        Self { path: path.into(), items: Mutex::new(Vec::new()) }
    }
}

impl Clone for Html {
    fn clone(&self) -> Self {
        Self { path: self.path.clone(), items: Mutex::new(Vec::new()) }
    }
}

#[async_trait::async_trait]
impl Sink for Html {
    fn kind(&self) -> SinkMedium {
        SinkMedium::Html
    }

    async fn write(&self, items: &[&Bookmark]) -> Result<SinkReport> {
        let mut buffer = self
            .items
            .lock()
            .map_err(|_| mbm_core::Error::Sink("the html sink's buffer is poisoned".to_owned()))?;
        buffer.extend(items.iter().map(|b| (*b).clone()));
        Ok(SinkReport::default())
    }

    async fn finish(&self) -> Result<SinkReport> {
        let items = {
            let mut buffer = self.items.lock().map_err(|_| {
                mbm_core::Error::Sink("the html sink's buffer is poisoned".to_owned())
            })?;
            std::mem::take(&mut *buffer)
        };
        let count = items.len();
        let refs: Vec<&Bookmark> = items.iter().collect();
        write_to(&self.path, document(&refs).as_bytes())?;
        Ok(SinkReport { written: count, files: 1, ..SinkReport::default() })
    }
}
